# Generated by Django 2.2.16 on 2020-10-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='galeria'),
        ),
    ]
