# Generated by Django 2.2.16 on 2020-10-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWash', '0002_galeria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=200, null=True)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
