# Generated by Django 2.2.16 on 2020-10-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWash', '0003_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='slider')),
            ],
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='galeria',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
