# Generated by Django 2.2.16 on 2020-10-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarWash', '0006_auto_20201013_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='mision',
            old_name='mision',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='vision',
            old_name='mision',
            new_name='descripcion',
        ),
    ]
