# Generated by Django 2.2.16 on 2020-10-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWash', '0007_auto_20201013_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='misionVision',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('imagenMision', models.ImageField(null=True, upload_to='misionVision')),
                ('vision', models.TextField()),
                ('imagenVision', models.ImageField(null=True, upload_to='misionVision')),
            ],
        ),
        migrations.DeleteModel(
            name='Mision',
        ),
        migrations.DeleteModel(
            name='Vision',
        ),
    ]
