# Generated by Django 2.2.16 on 2020-10-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarWash', '0008_auto_20201013_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misionvision',
            old_name='imagenMision',
            new_name='imagen_Mision',
        ),
        migrations.RenameField(
            model_name='misionvision',
            old_name='imagenVision',
            new_name='imagen_Vision',
        ),
    ]
