# Generated by Django 2.2.16 on 2020-10-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StarWash', '0009_auto_20201015_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misionvision',
            old_name='imagen_Mision',
            new_name='imagenMision',
        ),
        migrations.RenameField(
            model_name='misionvision',
            old_name='imagen_Vision',
            new_name='imagenVision',
        ),
    ]
