# Generated by Django 3.1.3 on 2020-11-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarWash', '0011_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
